use std::env;
use std::fs;
use std::path::Path;

/// Walk `site/` (the default seed site) and emit a Rust array that embeds
/// every file via `include_str!`, so `mdweb create` can copy it out and the
/// default theme can be read from it at runtime.
fn main() {
    let root = Path::new("site");
    if !root.is_dir() {
        println!("cargo:warning=missing site/ directory at repo root");
        return;
    }
    let mut files: Vec<(String, String)> = Vec::new();
    walk(root, root, &mut files);
    files.sort();

    let mut out = String::new();
    out.push_str(
        "// @generated by build.rs from the site/ directory. Do not edit.\n\
         pub const FILES: &[(&str, &str)] = &[\n",
    );
    for (rel, abs) in &files {
        out.push_str(&format!("    ({rel:?}, include_str!({abs:?})),\n"));
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(Path::new(&out_dir).join("site_files.rs"), out).expect("write site_files.rs");

    println!("cargo:rerun-if-changed=site");
    println!("cargo:rerun-if-changed=build.rs");
}

fn walk(base: &Path, dir: &Path, files: &mut Vec<(String, String)>) {
    for entry in fs::read_dir(dir).expect("read dir") {
        let entry = entry.expect("entry");
        let p = entry.path();
        if p.is_dir() {
            walk(base, &p, files);
        } else if p.is_file() {
            if String::from_utf8(fs::read(&p).expect("read file for embedding")).is_err() {
                // include_str! requires UTF-8, so skip binary files (fonts, images)
                continue;
            }
            let rel = p
                .strip_prefix(base)
                .expect("strip")
                .to_string_lossy()
                .replace('\\', "/");
            // include_str! is relative to the file it appears in (OUT_DIR),
            // so embed absolute paths resolved from the package root.
            let abs = std::env::current_dir()
                .expect("cwd")
                .join(&p)
                .to_string_lossy()
                .replace('\\', "/");
            files.push((rel, abs.clone()));
            let watch = abs.replace('"', "\\\"");
            println!("cargo:rerun-if-changed={watch}");
        }
    }
}
